INSERT INTO POSTS (USER_ID, BODY)
VALUES (2, "HELLO");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (3, "HELLO 2U TOO");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (1, "Hello everyone!");

UPDATE POSTS 
SET BODY = "to delete"
WHERE ID >= 7 AND ID <= 9;

DELETE FROM POSTS
WHERE ID >= 7 AND ID <= 9;

SELECT * FROM POSTS;